# Generated by Django 6.0.7 on 2026-07-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='dictionary',
            new_name='vocabulary',
        ),
    ]
